kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    environment:
      RUST_BACKTRACE: 1
    volumes:
      - name: binaries
        path: /tmp/binaries
      - name: identities
        path: /tmp/identities
    commands:
      - DEBIAN_FRONTEND='noninteractive' apt-get update && apt install -y libarchive-tools bc libelf-dev flex bison
      - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 11 && rm llvm.sh
      - export KERNEL_VERSION=$(uname -r)
      - ./scripts/build.sh ${KERNEL_VERSION%-*-*}
      - cargo install --path packet-generator --root .
      - cp ./bin/* /tmp/binaries
      - cp ./scripts/wait_until.sh /tmp/binaries
      - cp ./scripts/ci_test.sh /tmp/binaries
      - cp identity_*.json /tmp/identities

  - name: tezedge
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    # need privileged to run firewall
    privileged: true
    detach: true
    volumes:
      - name: binaries
        path: /tmp/binaries
    commands:
      # intensionally low complexity 18.0
      - /tmp/binaries/firewall-* -d eth0 --target=18.0 &
      - sleep 1
      - /tmp/binaries/fw node 9732
      - git clone https://github.com/simplestaking/tezedge
      - cd tezedge
      - git checkout tags/v0.7.2 -b v0.7.2
      - ./run.sh release

  - name: wait_for_tezedge
    image: ubuntu:20.04
    pull: if-not-exists
    volumes:
      - name: binaries
        path: /tmp/binaries
    commands:
      - DEBIAN_FRONTEND='noninteractive' apt-get update && apt install -y curl
      - /tmp/binaries/wait_until.sh tezedge:18732

  - name: test_bad_pow
    image: simplestakingcom/tezedge-ci-builder:latest
    pull: if-not-exists
    volumes:
      - name: binaries
        path: /tmp/binaries
      - name: identities
        path: /tmp/identities
    commands:
      - IDENTITIES=/tmp/identities BINARIES=/tmp/binaries /tmp/binaries/ci_test.sh tezedge:9732

volumes:
  - name: binaries
    temp: {}
  - name: identities
    temp: {}
