version: "3"

services:
  firewall:
    image: simplestakingcom/tezedge-firewall:v0.1.3
    build: .
    environment:
      - RUST_BACKTRACE=1
    privileged: true
    entrypoint: ./scripts/run.sh -d eth0 --target=26.0
    logging:
      driver: "none"

  node:
    image: tezos/tezos:v8.0
    depends_on:
      - firewall
    logging:
      driver: "none"
    network_mode: "service:firewall"
    entrypoint: tezos-node run --rpc-addr 0.0.0.0:8732

  tester-connect:
    image: simplestakingcom/tezedge-firewall-tester:v0.1.3
    build:
      context: tester
      dockerfile: Dockerfile
    depends_on:
      - node
    entrypoint: sh -c "./wait_until.sh firewall:8732 && ./test basic_connect --nocapture"

  tester-block:
    image: simplestakingcom/tezedge-firewall-tester:v0.1.3
    build:
      context: tester
      dockerfile: Dockerfile
    depends_on:
      - tester-connect
    entrypoint: sh -c "./wait_until.sh firewall:8732 && ./test basic_block --nocapture"
