version: "3"

services:
  firewall:
    build:
      context: .
      args:
        COMPLEXITY: 26.0
    privileged: true
    volumes:
      - "storage:/tmp"

  rust-node:
    image: simplestakingcom/tezedge:v0.7.2
    depends_on:
      - firewall
    logging:
      driver: "none"
    network_mode: "service:firewall"
    volumes:
      - "storage:/tmp"

  test_pow_reuse:
    build:
      context: .
      dockerfile: packet-generator.dockerfile
    depends_on:
      - rust-node
    volumes:
      - "storage:/tmp"
    entrypoint: sh -c "./scripts/test_pow_reuse.sh"

  test_bad_pow:
    build:
      context: .
      dockerfile: packet-generator.dockerfile
    depends_on:
      - rust-node
    volumes:
      - "storage:/tmp"
    entrypoint: sh -c "./scripts/test_bad_pow.sh"

volumes:
  storage:
    external: false
