version: "3"

services:
  firewall:
    image: simplestakingcom/tezedge-firewall:v0.1
    build: .
    privileged: true
    entrypoint: ./scripts/run.sh -d eth0 --target=26.0

  node:
    image: tezos/tezos:v8.0
    depends_on:
      - firewall
    logging:
      driver: "none"
    network_mode: "service:firewall"
    entrypoint: tezos-node run --rpc-addr 0.0.0.0:8732

  test_proof_of_work:
    build:
      context: .
      dockerfile: packet-generator.dockerfile
    depends_on:
      - node
    entrypoint: sh -c "./scripts/wait_until.sh firewall:8732 && ./scripts/test_bad_pow.sh"
