version: "3"

services:
  firewall:
    image: simplestakingcom/tezedge-firewall:v0.1.3
    privileged: true
    volumes:
      - "storage:/tmp"
    entrypoint: ./bin/firewall-5.8.18 -d eth0 --target=26.0

  rust-node:
    image: simplestakingcom/tezedge:v0.9.1
    depends_on:
      - firewall
    network_mode: "service:firewall"
    volumes:
      - "storage:/tmp"

volumes:
  storage:
    external: false
