version: "3"

services:
  firewall:
    build: .
    privileged: true
    networks:
      - firewall-network
    volumes:
      - "storage:/tmp"
    # TODO:
    entrypoint: sh -c "./firewall-5.8.18 -d eth0 & sleep 1 && ./fw node 9732 && sleep inf"

  rust-node:
    image: simplestakingcom/tezedge:v0.5.0
    depends_on:
      - firewall
    network_mode: "service:firewall"
    volumes:
      - "storage:/tmp"
    entrypoint: /home/appuser/tezedge/docker/compose/tezedge.sh

  packet-generator:
    build:
      context: .
      dockerfile: packet-generator.dockerfile
    depends_on:
      - rust-node
    networks:
      - firewall-network
    volumes:
      - "storage:/tmp"
    entrypoint: sh -c "./scripts/packet_generator.sh firewall 9732"

volumes:
  storage:
    external: false

networks:
  firewall-network:
    driver: bridge
    internal: true
