version: "3"

services:
  firewall:
    image: simplestakingcom/tezedge-firewall:v0.1
    build: .
    privileged: true
    entrypoint: ./scripts/run.sh -d eth0 --target=26.0

  node:
    image: simplestakingcom/tezedge:v0.7.2
    depends_on:
      - firewall
    logging:
      driver: "none"
    network_mode: "service:firewall"

  test_proof_of_work:
    image: simplestakingcom/tezedge-firewall-tests:v0.1
    build:
      context: .
      dockerfile: packet-generator.dockerfile
    depends_on:
      - node
    entrypoint: sh -c "./scripts/wait_until.sh firewall:18732 && ./scripts/test_bad_pow.sh"
