version: "3"

services:
  firewall:
    build: .
    privileged: true
    volumes:
      - "storage:/tmp"

  rust-node:
    image: simplestakingcom/tezedge:v0.7.2
    depends_on:
      - firewall
    logging:
      driver: "none"
    network_mode: "service:firewall"
    volumes:
      - "storage:/tmp"

  packet-generator:
    build:
      context: .
      dockerfile: packet-generator.dockerfile
    depends_on:
      - rust-node
    volumes:
      - "storage:/tmp"
    #entrypoint: sh -c "./scripts/packet_generator.sh firewall 9732"

volumes:
  storage:
    external: false
