version: "3"

services:
  firewall:
    build:
      context: .
      args:
        kernel_version: ${KERNEL_VERSION}
    privileged: true
    networks:
      - firewall-network
    volumes:
      - "socket:/tmp"
    entrypoint: sh -c "cd tezedge && SODIUM_USE_PKG_CONFIG=1 ./run.sh release & ./bpf-firewall/target/debug/firewall -d eth0"

  packet-generator:
    build:
      context: .
      dockerfile: packet-generator.dockerfile
    depends_on:
      - firewall
    networks:
      - firewall-network
    volumes:
      - "socket:/tmp"
    entrypoint: sh -c "sleep 5 && cd bpf-firewall && ./target/debug/packet-generator --address firewall:9732"

volumes:
  socket:
    external: false

networks:
  firewall-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge