version: "3"

services:
  firewall:
    build: .
    privileged: true
    volumes:
      - "storage:/tmp"
    entrypoint: ./scripts/run.sh -d eth0 --target=26.0

  rust-node:
    image: simplestakingcom/tezedge:v0.7.2
    depends_on:
      - firewall
    logging:
      driver: "none"
    network_mode: "service:firewall"
    volumes:
      - "storage:/tmp"

  ocaml-node:
    image: tezos/tezos:v7.5
    hostname: node
    volumes:
      - node_data:/var/run/tezos
    entrypoint: tezos-node

  #test_pow_reuse:
  #  build:
  #    context: .
  #    dockerfile: packet-generator.dockerfile
  #  depends_on:
  #    - rust-node
  #  entrypoint: sh -c "./scripts/test_pow_reuse.sh"

  #test_bad_pow:
  #  build:
  #    context: .
  #    dockerfile: packet-generator.dockerfile
  #  depends_on:
  #    - rust-node
  #  entrypoint: sh -c "./scripts/test_bad_pow.sh"

volumes:
  storage:
    external: false
  node_data:
    external: true
