version: "3"

services:
  firewall:
    build:
      context: .
      args:
        kernel_version: ${KERNEL_VERSION}
    privileged: true
    networks:
      - firewall-network
    volumes:
      - "storage:/tmp"
    entrypoint: sh -c "./bpf-firewall/target/debug/firewall -d eth0"

  rust-node:
    image: simplestakingcom/tezedge:v0.5.0
    depends_on:
      - firewall
    network_mode: "service:firewall"
    volumes:
      - "storage:/tmp"
    entrypoint: /home/appuser/tezedge/docker/compose/tezedge.sh

  packet-generator:
    build:
      context: .
      dockerfile: packet-generator.dockerfile
    depends_on:
      - rust-node
    networks:
      - firewall-network
    volumes:
      - "storage:/tmp"
    entrypoint: sh -c "cd bpf-firewall && ./target/debug/packet-generator --address firewall:9732"

volumes:
  storage:
    external: false

networks:
  firewall-network:
    driver: bridge
    internal: true
