version: "3"

services:
  firewall:
    image: simplestakingcom/tezedge-firewall:v0.1
    privileged: true
    volumes:
      - "storage:/tmp"
    entrypoint: ./scripts/run.sh -d eth0 --target=26.0

  rust-node:
    image: simplestakingcom/tezedge:v0.7.2
    depends_on:
      - firewall
    network_mode: "service:firewall"
    volumes:
      - "storage:/tmp"


volumes:
  storage:
    external: false
